
  steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['login', '-u', '_json_key', '-p', '$$GOOGLE_APPLICATION_CREDENTIALS', 'asia-southeast2.gcr.io']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-southeast2.gcr.io/$PROJECT_ID/pdf-translate-repo/pdf-translate:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast2.gcr.io/$PROJECT_ID/pdf-translate-repo/pdf-translate:latest']
images:
- 'asia-southeast2.gcr.io/$PROJECT_ID/pdf-translate-repo/pdf-translate:latest'