steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/document-translate-patrick/pdf-translate-image:latest', '.']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'gcloud' # Use 'gcloud' instead of 'run'
  - 'run'
  - 'deploy'
  - 'pdf-translate-image'
  - '--image'
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/document-translate-patrick/pdf-translate-image'
  - '--region'
  - 'asia-southeast2'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'