steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pdf-translate-image', '.']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'run'
  - 'deploy'
  - 'pdf-translate-image'
  - '--image'
  - 'gcr.io/$PROJECT_ID/pdf-translate-image'
  - '--region'
  - 'asia-southeast2'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'